# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='songDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('name_of_song', models.CharField(max_length=100)),
                ('hash_code', models.CharField(max_length=34)),
                ('score', models.CharField(default=b' ', max_length=1000)),
                ('email_id', models.EmailField(max_length=254)),
                ('karaoke_created', models.IntegerField(default=0)),
                ('email_sent', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=500)),
            ],
        ),
    ]
